### ISSUE TITLE
Any interest in merging this or relying on mongoid-compatibility?

### ISSUE THREAD

**Issue by dblock** [johnnyshields/mongoid_monkey#6]
https://github.com/mongoid/mongoid-compatibility

There seems to be a fair amount of code dealing with similar issues.

**Comment by johnnyshields** [comment]
Meh the goal is different than mongoid-compat in the sense that this changes the behavior of mongoid itself, and its potentially dangerous, so think they should be separate.

As for adding a dependency on mongoid compat... mongoid compat just adds version checking which is pretty trivial so don't see the need for it at the moment.
